// Common Pakistani cities/areas for the signup dropdown.
// Keep ordered alphabetically for usability.
export const PAKISTAN_AREAS = [
  "Abbottabad",
  "Bahawalpur",
  "Faisalabad",
  "Gilgit",
  "Gujranwala",
  "Gujrat",
  "Hyderabad",
  "Islamabad",
  "Jhelum",
  "Karachi",
  "Kasur",
  "Lahore",
  "Larkana",
  "Mardan",
  "Mingora",
  "Mirpur (AJK)",
  "Multan",
  "Muzaffarabad",
  "Muzaffargarh",
  "Nawabshah",
  "Okara",
  "Peshawar",
  "Quetta",
  "Rahim Yar Khan",
  "Rawalpindi",
  "Sahiwal",
  "Sargodha",
  "Sheikhupura",
  "Sialkot",
  "Skardu",
  "Sukkur",
  "Turbat",
  "Wah Cantt",
] as const;

export type PakistanArea = (typeof PAKISTAN_AREAS)[number];
